title: I want go home!!
description: 카렌 블로그
author: karen
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://lekaren.github.io
about: Freelance developer

baseurl: ""
url: "https://lekaren.github.io"

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]